### ISSUE TITLE
Crash due to configuration

### ISSUE THREAD

**Issue by naixx** [thealeksandr/PFLockScreen-Android#30]
Since that configuration contains on click listener, app crashes when a user presses home button and configuration is being serialized during onSaveInstanceState

**Comment by thealeksandr** [comment]
@naixx thanks. Will check.

**Comment by MaximKulikov** [comment]
Guess i have same issue. I press forgot pin and went to another activity with my flow

`    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.beautycoder.pflockscreen.PFFLockScreenConfiguration)
        at android.os.Parcel.writeSerializable(Parcel.java:1394)
        at android.os.Parcel.writeValue(Parcel.java:1341)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:669)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:118)
        at android.os.Parcel.writeTypedList(Parcel.java:1112)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:50)
        at android.os.Parcel.writeParcelable(Parcel.java:1363)
        at android.os.Parcel.writeValue(Parcel.java:1268)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:669)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2931)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
     Caused by: java.io.NotSerializableException: travel.pay.billfold.mvp.authorization.presenter.-$$Lambda$AuthorizationActivityPresenter$4Yf9utT4oTxwhZX7TxB_LBUkjwU
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at android.os.Parcel.writeSerializable(Parcel.java:1389)`

**Comment by tefracky** [comment]
I have the same issue like @naixx

**Comment by thealeksandr** [comment]
@tefracky was you able to reproduce? I think it's not related to the listener. I think the crash is happening because if ```PFFLockScreenConfiguration implements Serializable``` then inner class should too. In this case it's a builder. So ```public static class Builder implements Serializable``` should fix the crash. But I can not check. I can not reproduce it.

**Comment by tefracky** [comment]
@thealeksandr I testet your solution, but it doesn't work.

**Comment by MaximKulikov** [comment]
confirm. `Builder implements Serializable`not working, but it seams `transient ` prevent crash
    `private transient View.OnClickListener mOnLeftButtonClickListener = null;`

**Comment by thealeksandr** [comment]
@MaximKulikov I starting to think it's  kindof wierd to have onclicklistener as part of configuration. If we not going to save it (And we can not) we just gonna loose it. I think View will still save this onclick listener on rotation and it all should work. But probably it will be cleaner to remove it from config.

**Comment by ContextGrid** [comment]
Hello @thealeksandr, This is a really serious problem please check and try to resolve it.

Currently, I found a temporary solution 
@Override
    protected void onPause() {
        super.onPause();
        finish();
    }
finish your lock activity at on pause method.

**Comment by thealeksandr** [comment]
should be solved with latest update
