### ISSUE TITLE
KeyStoreException

### ISSUE THREAD

**Issue by zzzSeMzzz** [thealeksandr/PFLockScreen-Android#42]
In api 28
when call onCodeCompleted in MODE_AUTH

2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err: javax.crypto.IllegalBlockSizeException
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2055)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.security.PFSecurityUtils.decode(PFSecurityUtils.java:135)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.security.PFFingerprintPinCodeHelper.checkPin(PFFingerprintPinCodeHelper.java:65)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.viewmodels.PFPinCodeViewModel.checkPin(PFPinCodeViewModel.java:31)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$6.onCodeCompleted(PFLockScreenFragment.java:311)
2019-09-21 11:53:36.606 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.views.PFCodeView.input(PFCodeView.java:84)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$1.onClick(PFLockScreenFragment.java:187)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at android.view.View.performClick(View.java:6597)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at android.view.View.performClickInternal(View.java:6574)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at android.view.View.access$3100(View.java:778)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
2019-09-21 11:53:36.607 6732-6732/ru.sem.migrant W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-09-21 11:53:36.611 6732-6732/ru.sem.migrant W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-09-21 11:53:36.611 6732-6732/ru.sem.migrant W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-09-21 11:53:36.612 6732-6732/ru.sem.migrant W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2019-09-21 11:53:36.612 6732-6732/ru.sem.migrant W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-09-21 11:53:36.613 6732-6732/ru.sem.migrant W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-09-21 11:53:36.613 6732-6732/ru.sem.migrant W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-21 11:53:36.614 6732-6732/ru.sem.migrant W/System.err: Caused by: android.security.KeyStoreException: Unknown error
2019-09-21 11:53:36.614 6732-6732/ru.sem.migrant W/System.err:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
2019-09-21 11:53:36.614 6732-6732/ru.sem.migrant W/System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
2019-09-21 11:53:36.614 6732-6732/ru.sem.migrant W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)

**Comment by joyceHong0524** [comment]
I have the same issue :(  it must have been a change in android Keystore system

**Comment by thealeksandr** [comment]
@zzzSeMzzz @joyceHong0524 looking into it

**Comment by thealeksandr** [comment]
@zzzSeMzzz @joyceHong0524 can you provide more details. What phone you using? What code length you trying to decrypt? Is it happens in 100% cases?

**Comment by joyceHong0524** [comment]
@thealeksandr It has been a while I got that error so I actually don't remember when it exactly happens but I was using Galaxy Note10 with Android 9. I will re-check the problem and give you more details if I have time

**Comment by kirkkhua** [comment]
I have the same error on Google Nexus 5 with Android 6.0.1

**Comment by rasoulmiri** [comment]
W/System.err: javax.crypto.IllegalBlockSizeException
W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2055)
W/System.err:     at com.beautycoder.pflockscreen.security.PFSecurityUtils.decode(PFSecurityUtils.java:135)
W/System.err:     at com.beautycoder.pflockscreen.security.PFFingerprintPinCodeHelper.checkPin(PFFingerprintPinCodeHelper.java:65)
W/System.err:     at com.beautycoder.pflockscreen.viewmodels.PFPinCodeViewModel.checkPin(PFPinCodeViewModel.java:33)
W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$6.onCodeCompleted(PFLockScreenFragment.java:343)
W/System.err:     at com.beautycoder.pflockscreen.views.PFCodeView.input(PFCodeView.java:85)
W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$1.onClick(PFLockScreenFragment.java:219)
W/System.err:     at android.view.View.performClick(View.java:7352)
W/System.err:     at android.widget.TextView.performClick(TextView.java:14177)
W/System.err:     at android.view.View.performClickInternal(View.java:7318)
W/System.err:     at android.view.View.access$3200(View.java:846)
W/System.err:     at android.view.View$PerformClick.run(View.java:27800)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
W/System.err: Caused by: android.security.KeyStoreException: Unknown error
W/System.err:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:1177)
W/System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
W/System.err: 	... 19 more


SUMSUNG Gakaxy S8 Android 9

**Comment by thealeksandr** [comment]
@rasoulmiri can you reproduce with example project? (If you pull git repository and try to build it?)

**Comment by thealeksandr** [comment]
@rasoulmiri can you reproduce with example project? (If you pull git repository and try to build it?)
