### ISSUE TITLE
Parcelable encountered IOException writing serializable object

### ISSUE THREAD

**Issue by ildarg** [thealeksandr/PFLockScreen-Android#46]
Runtime Exception if user hides PIN form.

Press Home button when PIN code entering form is active

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: XXXXXX, PID: 6132
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.beautycoder.pflockscreen.PFFLockScreenConfiguration)
        at android.os.Parcel.writeSerializable(Parcel.java:1762)
        at android.os.Parcel.writeValue(Parcel.java:1710)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:777)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506)
        at android.os.Bundle.writeToParcel(Bundle.java:1181)
        at android.os.Parcel.writeBundle(Parcel.java:817)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:169)
        at android.os.Parcel.writeTypedObject(Parcel.java:1564)
        at android.os.Parcel.writeTypedList(Parcel.java:1297)
        at android.os.Parcel.writeTypedList(Parcel.java:1282)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1731)
        at android.os.Parcel.writeValue(Parcel.java:1637)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:777)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506)
        at android.os.Bundle.writeToParcel(Bundle.java:1181)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4617)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3998)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.io.NotSerializableException: ru.etsoft.aps.MainActivity$5
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1233)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1597)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1558)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at android.os.Parcel.writeSerializable(Parcel.java:1757)
        at android.os.Parcel.writeValue(Parcel.java:1710) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:777) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506) 
        at android.os.Bundle.writeToParcel(Bundle.java:1181) 
        at android.os.Parcel.writeBundle(Parcel.java:817) 
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:169) 
        at android.os.Parcel.writeTypedObject(Parcel.java:1564) 
        at android.os.Parcel.writeTypedList(Parcel.java:1297) 
        at android.os.Parcel.writeTypedList(Parcel.java:1282) 
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51) 
        at android.os.Parcel.writeParcelable(Parcel.java:1731) 
        at android.os.Parcel.writeValue(Parcel.java:1637) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:777) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506) 
        at android.os.Bundle.writeToParcel(Bundle.java:1181) 
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4617) 
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3998) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

 - Device: emulator
 - OS: Android 8.0
 - Library version implementation 'com.github.thealeksandr:PFLockScreen-Android:1.0.0-beta5'

**Comment by MaximKulikov** [comment]
build project from this commit, it been fixed
https://github.com/thealeksandr/PFLockScreen-Android/commit/f5247a0fbdcc80e2838d380f26e5096151f1fdad

**Comment by thealeksandr** [comment]
@MaximKulikov @ildarg Updated version with this commit
