### ISSUE TITLE
BadPaddingException in AUTH mode

### ISSUE THREAD

**Issue by kirkkhua** [thealeksandr/PFLockScreen-Android#49]
I'm getting the issue (W/System.err) in Logcat when I finish entering 4-digit PIN code.

**To Reproduce**:
1) Set up the PIN code in MODE_CREATE;
2) Go to the screen that requests PIN code in MODE_AUTH; 
3) Enter 4 digits of PIN code and see the Logcat.

**Expected behavior** One of the methods responsible for detecting correct / incorrect PIN code called.

**Smartphone**:
- Device: Xiaomi Redmi 4X
- OS: Android 7.1.2
- Library version Version: API 25

**Additional context**

```
2019-11-13 15:53:03.163 W/System.err: javax.crypto.BadPaddingException
2019-11-13 15:53:03.165 W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:515)
2019-11-13 15:53:03.165 W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2056)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.security.PFSecurityUtils.decode(PFSecurityUtils.java:135)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.security.PFFingerprintPinCodeHelper.checkPin(PFFingerprintPinCodeHelper.java:65)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.viewmodels.PFPinCodeViewModel.checkPin(PFPinCodeViewModel.java:31)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$6.onCodeCompleted(PFLockScreenFragment.java:311)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.views.PFCodeView.input(PFCodeView.java:84)
2019-11-13 15:53:03.165 W/System.err:     at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$1.onClick(PFLockScreenFragment.java:187)
2019-11-13 15:53:03.165 W/System.err:     at android.view.View.performClick(View.java:5647)
2019-11-13 15:53:03.165 W/System.err:     at android.view.View$PerformClick.run(View.java:22465)
2019-11-13 15:53:03.165 W/System.err:     at android.os.Handler.handleCallback(Handler.java:754)
2019-11-13 15:53:03.165 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-11-13 15:53:03.165 W/System.err:     at android.os.Looper.loop(Looper.java:163)
2019-11-13 15:53:03.165 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6238)
2019-11-13 15:53:03.165 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-13 15:53:03.166 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
2019-11-13 15:53:03.166 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
2019-11-13 15:53:03.166 W/System.err: Caused by: android.security.KeyStoreException: Invalid argument
2019-11-13 15:53:03.166 W/System.err:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
2019-11-13 15:53:03.166 W/System.err:     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
2019-11-13 15:53:03.166 W/System.err:     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
2019-11-13 15:53:03.166 W/System.err: 	... 16 more
```

**Comment by thealeksandr** [comment]
@kirkkhua thanks for the info. I'll take a look

**Comment by kirkkhua** [comment]
> @kirkkhua thanks for the info. I'll take a look

Hi @thealeksandr! Maybe I can help you in fixing the problem in any way? I can provide any additional info or possibly follow your instructions in order to find a solution for errors mentioned above. Thank you!

**Comment by thealeksandr** [comment]
@kirkkhua can you reproduce other versions or other devices?

**Comment by thealeksandr** [comment]
@kirkkhua can you reproduce if you download source code and install example app?Create code and then unlock? 
And are you using fingerprint to unlock or just code?

**Comment by thealeksandr** [comment]
Trying to understand if there is something different in the flow/order of operation.

**Comment by kirkkhua** [comment]
@thealeksandr thanks for your reply! It's strange, but when I download the project as is (as a ZIP) and just open it, I can successfully set the pin code and then enter it without any errors. I think that there must be something in the difference of the ways the library is included in a project config. As soon as I have more info, I'll comment here.

**Comment by thealeksandr** [comment]
@kirkkhua Can not reproduce right now. Can something be different in a flow? The way you called library methods or order how you called them? Maybe there is some edge case I didn't think about.

**Comment by kirkkhua** [comment]
@thealeksandr when I opened the example project and copy-pasted everything from it in exactly the same sequence, everything worked on my end. Possibly an example given on Wiki page somehow caused problems in my Kotlin application. Thanks for your help and suggestions!

**Comment by thealeksandr** [comment]
@kirkkhua Were you able to find the difference between example and your project? 
Is it the same as https://github.com/thealeksandr/PFLockScreen-Android/issues/42 ?

**Comment by kirkkhua** [comment]
@thealeksandr I ended up with conclusion that this error was my mistake. I followed your example project and implemented everything in mine by copy-pasting the code, and it worked!

**Comment by thealeksandr** [comment]
@kirkkhua so you don't know what was the error. Just curious if I can protect from it from the library

**Comment by kirkkhua** [comment]
@thealeksandr unfortunately I don't remember exactly, but that was certainly me implementing the library and the code related to it in a wrong way.
