### ISSUE TITLE
Failure saving state for Fingerprint Dialog

### ISSUE THREAD

**Issue by muhammadnomany25** [thealeksandr/PFLockScreen-Android#50]
When Success auth with fingerprint, the app get crashed and this is the error log:
`Failure saving state: active PFFingerprintAuthDialogFragment{b9bfe35 (7135379e-5e81-47c8-aef9-ff2d63cd623c) dg} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1503)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4943)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4231)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4290)
        at android.app.ActivityThread.-wrap28(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by itsaxay** [comment]
onAuthenticated - while dismiss fragment

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.b(FragmentManagerImpl.java:11)
       at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:2)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:2)
       at androidx.fragment.app.FragmentManagerImpl.allocBackStackIndex(FragmentManagerImpl.java:1)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:1)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:9)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:8)
       at com.beautycoder.pflockscreen.fragments.PFLockScreenFragment$4$1.onAuthenticated(PFLockScreenFragment.java:8)
       at com.beautycoder.pflockscreen.fragments.PFFingerprintUIHelper$2.run(PFFingerprintUIHelper.java:8)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```
